# Generated by Django 4.2 on 2023-04-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_logo', models.ImageField(upload_to='media/%Y/%md/%d', verbose_name='Upload Logo')),
                ('food_zone_address', models.CharField(max_length=70, verbose_name='Food Zone Address')),
                ('food_zone_phone', models.CharField(max_length=50, verbose_name='Food Zone Phone Number')),
                ('food_zone_email', models.EmailField(max_length=254, verbose_name='Food Zone Email')),
            ],
            options={
                'verbose_name': 'Control Model',
                'verbose_name_plural': 'Control Model',
            },
        ),
    ]
