# Generated by Django 4.2 on 2023-04-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_title', models.CharField(max_length=50, verbose_name='Set About Us Top Title')),
                ('about_us_txt', models.TextField(verbose_name='Set About Us Text')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='IndexPageAssortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assortment_title', models.CharField(max_length=50, verbose_name='Set Assortment Title')),
                ('assortment_shawarma', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Set Shawarma Image')),
                ('assortment_soft_drinks', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Set Soft Drinks Image')),
                ('assortment_barbeque', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Set Barbeque Image')),
                ('assortment_lahmajo', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Set Lahmajo Image')),
                ('assortment_gril', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Set Gril Image')),
                ('assortment_beer', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Set Beer Image')),
            ],
            options={
                'verbose_name': 'Assortment',
                'verbose_name_plural': 'Assortment',
            },
        ),
        migrations.CreateModel(
            name='IndexPageRefreshedMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshed_menu_item_image', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Set Refreshed Menu Item Image')),
                ('refreshed_menu_item_title', models.CharField(max_length=50, verbose_name='Set Refreshed Menu Item Title')),
                ('refreshed_menu_item_text', models.CharField(max_length=50, verbose_name='Set Refreshed Menu Item Title')),
            ],
            options={
                'verbose_name': 'Refreshed Menu',
                'verbose_name_plural': 'Refreshed Menu',
            },
        ),
        migrations.CreateModel(
            name='IndexPageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Upload Slider Image')),
                ('slider_title', models.CharField(max_length=50, verbose_name='Set Slider Title')),
            ],
            options={
                'verbose_name': 'Index Page Slider',
                'verbose_name_plural': 'Index Page Slider',
            },
        ),
    ]
