# Generated by Django 4.2 on 2023-04-22 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
