# Generated by Django 4.2 on 2023-04-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Upload Image')),
                ('about_us_title', models.CharField(max_length=50, verbose_name='Set About Us Title')),
                ('about_us_txt', models.TextField(verbose_name='Set About Us Text')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Upload Menu Item Image')),
                ('menu_item_name', models.CharField(max_length=50, verbose_name='Set Menu Item Nem')),
                ('menu_item_title', models.CharField(max_length=50, verbose_name='Set Menu Item Text')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.DeleteModel(
            name='IndexPageAboutUs',
        ),
    ]
