# Generated by Django 4.2 on 2023-04-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about_menu_delete_indexpageaboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicmodel',
            name='food_zone_facebook',
            field=models.URLField(null=True, verbose_name='Set Facebook Url'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='food_zone_glovo',
            field=models.URLField(null=True, verbose_name='Set Glovo Url'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='food_zone_instagram',
            field=models.URLField(null=True, verbose_name='Set Instagram Url'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='food_zone_work_hours_end',
            field=models.IntegerField(null=True, verbose_name='Food Zone Work Hours End'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='food_zone_work_hours_start',
            field=models.IntegerField(null=True, verbose_name='Food Zone Work Hours Start'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='food_zone_yandex_eat',
            field=models.URLField(null=True, verbose_name='Set Yandex Eat Url'),
        ),
    ]
