# Generated by Django 4.2 on 2023-04-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_basicmodel_food_zone_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicmodel',
            name='food_zone_work_hours_end',
            field=models.CharField(max_length=70, null=True, verbose_name='Food Zone Work Hours End'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='food_zone_work_hours_start',
            field=models.CharField(max_length=70, null=True, verbose_name='Food Zone Work Hours Start'),
        ),
    ]
