# Generated by Django 4.2 on 2023-04-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_basicmodel_food_zone_work_hours_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծվելու Ամսաթիվ')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Email',
            },
        ),
    ]
