# Generated by Django 4.2 on 2023-04-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_hireus'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_item_price',
            field=models.IntegerField(null=True, verbose_name='Set Menu Item Price'),
        ),
    ]
