# Generated by Django 4.2 on 2023-04-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_menu_menu_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Menu Type'),
        ),
    ]
