# Generated by Django 4.2 on 2023-04-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_menubarbeque_menubeer_menudrinks_menugril_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menubarbeque',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='menubeer',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='menudrinks',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='menugril',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='menulahmajo',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='menushawarma',
            name='menu_type',
        ),
    ]
