# Generated by Django 4.2 on 2023-04-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_menu_menucategories_delete_menubarbeque_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategories',
            options={'verbose_name': 'Menu Categories', 'verbose_name_plural': 'Menu Categories'},
        ),
    ]
