# Generated by Django 4.2 on 2023-04-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_menucategories_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
    ]
