# Generated by Django 4.2 on 2023-04-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_menu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBarbeque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Upload Menu Item Image')),
                ('menu_item_name', models.CharField(max_length=50, verbose_name='Set Menu Item Nem')),
                ('menu_item_title', models.CharField(max_length=50, verbose_name='Set Menu Item Text')),
                ('menu_item_price', models.IntegerField(null=True, verbose_name='Set Menu Item Price')),
                ('is_published', models.BooleanField(null=True, verbose_name='Is Published ?')),
            ],
            options={
                'verbose_name': 'Menu Barbeque',
                'verbose_name_plural': 'Menu Barbeuqe',
            },
        ),
        migrations.CreateModel(
            name='MenuBeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Upload Menu Item Image')),
                ('menu_item_name', models.CharField(max_length=50, verbose_name='Set Menu Item Nem')),
                ('menu_item_title', models.CharField(max_length=50, verbose_name='Set Menu Item Text')),
                ('menu_item_price', models.IntegerField(null=True, verbose_name='Set Menu Item Price')),
                ('is_published', models.BooleanField(null=True, verbose_name='Is Published ?')),
            ],
            options={
                'verbose_name': 'Menu Beer',
                'verbose_name_plural': 'Menu Beer',
            },
        ),
        migrations.CreateModel(
            name='MenuDrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Upload Menu Item Image')),
                ('menu_item_name', models.CharField(max_length=50, verbose_name='Set Menu Item Nem')),
                ('menu_item_title', models.CharField(max_length=50, verbose_name='Set Menu Item Text')),
                ('menu_item_price', models.IntegerField(null=True, verbose_name='Set Menu Item Price')),
                ('is_published', models.BooleanField(null=True, verbose_name='Is Published ?')),
            ],
            options={
                'verbose_name': 'Menu Drniks',
                'verbose_name_plural': 'Menu Drniks',
            },
        ),
        migrations.CreateModel(
            name='MenuGril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Upload Menu Item Image')),
                ('menu_item_name', models.CharField(max_length=50, verbose_name='Set Menu Item Nem')),
                ('menu_item_title', models.CharField(max_length=50, verbose_name='Set Menu Item Text')),
                ('menu_item_price', models.IntegerField(null=True, verbose_name='Set Menu Item Price')),
                ('is_published', models.BooleanField(null=True, verbose_name='Is Published ?')),
            ],
            options={
                'verbose_name': 'Menu Beer',
                'verbose_name_plural': 'Menu Beer',
            },
        ),
        migrations.CreateModel(
            name='MenuLahmajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Upload Menu Item Image')),
                ('menu_item_name', models.CharField(max_length=50, verbose_name='Set Menu Item Nem')),
                ('menu_item_title', models.CharField(max_length=50, verbose_name='Set Menu Item Text')),
                ('menu_item_price', models.IntegerField(null=True, verbose_name='Set Menu Item Price')),
                ('is_published', models.BooleanField(null=True, verbose_name='Is Published ?')),
            ],
            options={
                'verbose_name': 'Menu Lahmajo',
                'verbose_name_plural': 'Menu Lahmajo',
            },
        ),
        migrations.CreateModel(
            name='MenuShawarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Upload Menu Item Image')),
                ('menu_item_name', models.CharField(max_length=50, verbose_name='Set Menu Item Nem')),
                ('menu_item_title', models.CharField(max_length=50, verbose_name='Set Menu Item Text')),
                ('menu_item_price', models.IntegerField(null=True, verbose_name='Set Menu Item Price')),
                ('is_published', models.BooleanField(null=True, verbose_name='Is Published ?')),
            ],
            options={
                'verbose_name': 'Menu Shawarma',
                'verbose_name_plural': 'Menu Shawarma',
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuCategories',
        ),
    ]
