# Generated by Django 4.2 on 2023-04-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_menubarbeque_menubeer_menudrinks_menugril_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageSliderActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Upload Slider Image')),
                ('slider_title', models.CharField(max_length=50, verbose_name='Set Slider Title')),
            ],
            options={
                'verbose_name': 'Index Page Slider Active',
                'verbose_name_plural': 'Index Page Slider Active',
            },
        ),
    ]
