# Generated by Django 4.2 on 2023-04-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_indexpageslider_is_published_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HireUs',
            new_name='Get_email',
        ),
    ]
