# Generated by Django 4.2 on 2023-04-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_hireus_get_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('txt', models.CharField(max_length=50, verbose_name='Text')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծվելու Ամսաթիվ')),
            ],
            options={
                'verbose_name': 'Messages',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
