# Generated by Django 4.2 on 2023-04-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_get_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_message',
            name='txt',
            field=models.TextField(verbose_name=''),
        ),
    ]
