# Generated by Django 4.2 on 2023-04-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_get_message_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_message',
            name='txt',
            field=models.TextField(null=True, verbose_name=''),
        ),
    ]
