# Generated by Django 4.2 on 2023-04-22 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_indexpagereviews_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagereviews',
            name='size',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
