# Generated by Django 4.2 on 2023-04-22 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_indexpagereviews_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpagereviews',
            name='size',
        ),
        migrations.AlterField(
            model_name='indexpagereviews',
            name='star',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
