# Generated by Django 4.2 on 2023-04-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_indexpagereviews_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagereviews',
            name='is_published',
            field=models.BooleanField(default=True, null=True, verbose_name='Is Published ? '),
        ),
    ]
