# Generated by Django 4.2 on 2023-04-22 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_indexpagereviews_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageReviewsActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Customer Review')),
                ('star', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('customer_info', models.CharField(max_length=50, verbose_name='Customer Name & Surname')),
                ('is_published', models.BooleanField(default=True, null=True, verbose_name='Is Published ? ')),
            ],
            options={
                'verbose_name': 'Reviews Active',
                'verbose_name_plural': 'Reviews Active',
            },
        ),
    ]
