# Generated by Django 4.2 on 2023-04-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_indexpagereviewsactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Upload Menu Item Image')),
                ('menu_item_name', models.CharField(max_length=50, verbose_name='Set Menu Item Nem')),
                ('menu_item_title', models.CharField(max_length=50, verbose_name='Set Menu Item Text')),
                ('menu_item_price', models.IntegerField(null=True, verbose_name='Set Menu Item Price')),
                ('is_published', models.BooleanField(null=True, verbose_name='Is Published ?')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Set Category')),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.DeleteModel(
            name='MenuBarbeque',
        ),
        migrations.DeleteModel(
            name='MenuBeer',
        ),
        migrations.DeleteModel(
            name='MenuDrinks',
        ),
        migrations.DeleteModel(
            name='MenuGril',
        ),
        migrations.DeleteModel(
            name='MenuLahmajo',
        ),
        migrations.DeleteModel(
            name='MenuShawarma',
        ),
        migrations.AddField(
            model_name='menu',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.menucategories'),
        ),
    ]
