# Generated by Django 4.2 on 2023-04-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_indexpageassortment_assortment_burger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpageassortment',
            name='assortment_barbeque_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Barbeque Title'),
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='assortment_beer_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Beer Title'),
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='assortment_burger_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Burger Title'),
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='assortment_gril_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Gril Title'),
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='assortment_lahmajo_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Lahmajo Title'),
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='assortment_shawarma_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Shawarma Title'),
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='assortment_soft_drinks_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Soft Drinks Title'),
        ),
    ]
