# Generated by Django 4.2 on 2023-04-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_indexpageassortment_assortment_barbeque_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_title', models.CharField(max_length=50, verbose_name='Set Title')),
                ('terms_txt', models.CharField(max_length=50, verbose_name='Set Title')),
            ],
            options={
                'verbose_name': 'Terms & Conditions',
                'verbose_name_plural': 'Terms & Conditions',
            },
        ),
    ]
