# Generated by Django 4.2 on 2023-04-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_get_message_captcha_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Get_message',
            new_name='FriendForm',
        ),
    ]
