# Generated by Django 4.2 on 2023-04-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_get_message_friendform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendForm',
            new_name='Friend',
        ),
    ]
