# Generated by Django 4.2 on 2023-04-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_get_message_alter_friend_options_remove_friend_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
