# Generated by Django 4.2 on 2023-04-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
