# Generated by Django 4.2 on 2023-04-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_delete_friend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Մեր Մասին', 'verbose_name_plural': 'Մեր Մասին'},
        ),
        migrations.AlterModelOptions(
            name='basicmodel',
            options={'verbose_name': 'Ղեկավարման Կետ', 'verbose_name_plural': 'Ղեկավարման Կետ'},
        ),
        migrations.AlterModelOptions(
            name='get_email',
            options={'verbose_name': 'Նոր Հետևորդներ', 'verbose_name_plural': 'Նոր Հետևորդներ'},
        ),
        migrations.AlterModelOptions(
            name='get_message',
            options={'verbose_name': 'Նամակներ', 'verbose_name_plural': 'Նամակներ'},
        ),
        migrations.AlterModelOptions(
            name='indexpageassortment',
            options={'verbose_name': 'Տեսականի', 'verbose_name_plural': 'Տեսականի'},
        ),
        migrations.AlterModelOptions(
            name='indexpagerefreshedmenu',
            options={'verbose_name': 'Թարմացված Մենյու', 'verbose_name_plural': 'Թարմացված Մենյու'},
        ),
        migrations.AlterModelOptions(
            name='indexpagereviews',
            options={'verbose_name': 'Կարծիքների Սլայդեր Պասիվ', 'verbose_name_plural': 'Կարծիքների Սլայդեր Պասիվ'},
        ),
        migrations.AlterModelOptions(
            name='indexpagereviewsactive',
            options={'verbose_name': 'Կարծիքների Սլայդեր Ակտիվ', 'verbose_name_plural': 'Կարծիքների Սլայդեր Ակտիվ'},
        ),
        migrations.AlterModelOptions(
            name='indexpageslider',
            options={'verbose_name': 'Գլխավոր Սլայդեր Պասիվ', 'verbose_name_plural': 'Գլխավոր Սլայդեր Պասիվ'},
        ),
        migrations.AlterModelOptions(
            name='indexpageslideractive',
            options={'verbose_name': 'Գլխավոր Սլայդեր Ակտիվ', 'verbose_name_plural': 'Գլխավոր Սլայդեր Ակտիվ'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Մենյու', 'verbose_name_plural': 'Մենյու'},
        ),
        migrations.AlterModelOptions(
            name='menucategories',
            options={'verbose_name': 'Մենյու Կատեգորիաներ', 'verbose_name_plural': 'Մենյու Կատեգորիաներ'},
        ),
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name': 'Կայքի Մասին', 'verbose_name_plural': 'Կայքի Մասին'},
        ),
    ]
