# Generated by Django 4.2 on 2023-04-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_about_options_alter_basicmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='get_email',
            options={'ordering': ['id'], 'verbose_name': 'Նոր Հետևորդներ', 'verbose_name_plural': 'Նոր Հետևորդներ'},
        ),
        migrations.AlterModelOptions(
            name='get_message',
            options={'ordering': ['id'], 'verbose_name': 'Նամակներ', 'verbose_name_plural': 'Նամակներ'},
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время изменения'),
        ),
    ]
