# Generated by Django 4.2 on 2023-04-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_get_email_options_alter_get_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_published',
            field=models.BooleanField(default=True, null=True, verbose_name='Is Published ?'),
        ),
        migrations.AddField(
            model_name='about',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='about',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время изменения'),
        ),
    ]
