# Generated by Django 4.2 on 2023-04-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_about_is_published_about_time_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='menu',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_us_title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
