# Generated by Django 4.2 on 2023-04-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_indexpagerefreshedmenu_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpagerefreshedmenu',
            options={'ordering': ['id'], 'verbose_name': 'Թարմացված Մենյու', 'verbose_name_plural': 'Թարմացված Մենյու'},
        ),
        migrations.AlterModelOptions(
            name='indexpagereviews',
            options={'ordering': ['id'], 'verbose_name': 'Կարծիքների Սլայդեր Պասիվ', 'verbose_name_plural': 'Կարծիքների Սլայդեր Պասիվ'},
        ),
        migrations.AlterModelOptions(
            name='indexpagereviewsactive',
            options={'ordering': ['id'], 'verbose_name': 'Կարծիքների Սլայդեր Ակտիվ', 'verbose_name_plural': 'Կարծիքների Սլայդեր Ակտիվ'},
        ),
        migrations.AlterModelOptions(
            name='indexpageslider',
            options={'ordering': ['id'], 'verbose_name': 'Գլխավոր Սլայդեր Պասիվ', 'verbose_name_plural': 'Գլխավոր Սլայդեր Պասիվ'},
        ),
        migrations.AlterModelOptions(
            name='indexpageslideractive',
            options={'ordering': ['id'], 'verbose_name': 'Գլխավոր Սլայդեր Ակտիվ', 'verbose_name_plural': 'Գլխավոր Սլայդեր Ակտիվ'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id'], 'verbose_name': 'Մենյու', 'verbose_name_plural': 'Մենյու'},
        ),
        migrations.AlterModelOptions(
            name='menucategories',
            options={'ordering': ['id'], 'verbose_name': 'Մենյու Կատեգորիաներ', 'verbose_name_plural': 'Մենյու Կատեգորիաներ'},
        ),
        migrations.AddField(
            model_name='indexpageslider',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='indexpageslider',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время изменения'),
        ),
        migrations.AddField(
            model_name='indexpageslideractive',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='indexpageslideractive',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='indexpageslider',
            name='is_published',
            field=models.BooleanField(default=True, null=True, verbose_name='Is Published ? '),
        ),
    ]
