# Generated by Django 4.2 on 2023-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_indexpagerefreshedmenu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_us_img',
            field=models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Նկար'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_us_title',
            field=models.CharField(max_length=50, verbose_name='Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='about',
            name='is_published',
            field=models.BooleanField(default=True, null=True, verbose_name='Տեղադրված է ՞'),
        ),
        migrations.AlterField(
            model_name='about',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='about',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='food_zone_address',
            field=models.CharField(max_length=70, verbose_name='Հասցե'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='food_zone_email',
            field=models.EmailField(max_length=254, verbose_name='Էլ-հասցե'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='food_zone_facebook',
            field=models.URLField(null=True, verbose_name='Facebook Հղում'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='food_zone_instagram',
            field=models.URLField(null=True, verbose_name='Instagram Հղում'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='food_zone_phone',
            field=models.CharField(max_length=50, verbose_name='Հեռ․համար'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='food_zone_work_hours_end',
            field=models.CharField(max_length=70, null=True, verbose_name='Աշխ․ավարտ'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='food_zone_work_hours_start',
            field=models.CharField(max_length=70, null=True, verbose_name='Աշխ․սկիզբ'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='page_logo',
            field=models.ImageField(upload_to='media/%Y/%md/%d', verbose_name='Ներբեռնել Նկար'),
        ),
        migrations.AlterField(
            model_name='indexpageassortment',
            name='assortment_barbeque_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Barbeque Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='indexpageassortment',
            name='assortment_beer_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Beer Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='indexpageassortment',
            name='assortment_burger_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Burger Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='indexpageassortment',
            name='assortment_gril_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Gril Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='indexpageassortment',
            name='assortment_lahmajo_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Lahmajo Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='indexpageassortment',
            name='assortment_shawarma_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Shawarma Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='indexpageassortment',
            name='assortment_soft_drinks_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Set Soft Drinks Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='indexpageassortment',
            name='assortment_title',
            field=models.CharField(max_length=50, verbose_name='Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='indexpagerefreshedmenu',
            name='is_published',
            field=models.BooleanField(default=True, null=True, verbose_name='Տեղադրված է ՞ '),
        ),
        migrations.AlterField(
            model_name='indexpagerefreshedmenu',
            name='refreshed_menu_item_image',
            field=models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Նկար'),
        ),
        migrations.AlterField(
            model_name='indexpagerefreshedmenu',
            name='refreshed_menu_item_text',
            field=models.CharField(max_length=50, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='indexpagerefreshedmenu',
            name='refreshed_menu_item_title',
            field=models.CharField(max_length=50, verbose_name='Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='indexpagerefreshedmenu',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='indexpagerefreshedmenu',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='indexpagereviews',
            name='is_published',
            field=models.BooleanField(default=True, null=True, verbose_name='Տեղադրված է ՞ '),
        ),
        migrations.AlterField(
            model_name='indexpagereviews',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='indexpagereviews',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='indexpagereviewsactive',
            name='customer_info',
            field=models.CharField(max_length=50, verbose_name='Հաճախորդի Մասին'),
        ),
        migrations.AlterField(
            model_name='indexpagereviewsactive',
            name='is_published',
            field=models.BooleanField(default=True, null=True, verbose_name='Տեղադրված է ՞ '),
        ),
        migrations.AlterField(
            model_name='indexpagereviewsactive',
            name='review',
            field=models.TextField(verbose_name='Մեկնաբանություն'),
        ),
        migrations.AlterField(
            model_name='indexpagereviewsactive',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='indexpagereviewsactive',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='indexpageslider',
            name='is_published',
            field=models.BooleanField(default=True, null=True, verbose_name='Տեղադրված է ՞ '),
        ),
        migrations.AlterField(
            model_name='indexpageslider',
            name='slider_title',
            field=models.CharField(max_length=50, verbose_name='Set Slider Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='indexpageslider',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='indexpageslider',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='indexpageslideractive',
            name='is_published',
            field=models.BooleanField(default=True, null=True, verbose_name='Տեղադրված է ՞'),
        ),
        migrations.AlterField(
            model_name='indexpageslideractive',
            name='slider_img',
            field=models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Նկար'),
        ),
        migrations.AlterField(
            model_name='indexpageslideractive',
            name='slider_title',
            field=models.CharField(max_length=50, verbose_name='Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='indexpageslideractive',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='indexpageslideractive',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_published',
            field=models.BooleanField(null=True, verbose_name='Տեղադրված է ՞'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_img',
            field=models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Նկար'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_item_name',
            field=models.CharField(max_length=50, verbose_name='Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_item_price',
            field=models.IntegerField(null=True, verbose_name='Գին'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_item_title',
            field=models.CharField(max_length=50, verbose_name='Տեքստ'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='terms_title',
            field=models.CharField(max_length=50, verbose_name='Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='terms_txt',
            field=models.CharField(max_length=50, verbose_name='Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
    ]
