# Generated by Django 4.2 on 2023-04-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_about_about_us_txt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_barbeque',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_barbeque_title',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_beer',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_beer_title',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_burger',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_burger_title',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_gril',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_gril_title',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_lahmajo',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_lahmajo_title',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_shawarma',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_shawarma_title',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_soft_drinks',
        ),
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='assortment_soft_drinks_title',
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='assortment_img',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Նկար'),
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='is_published',
            field=models.BooleanField(default=True, null=True, verbose_name='Տեղադրված է ՞ '),
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='indexpageassortment',
            name='assortment_title',
            field=models.CharField(max_length=50, null=True, verbose_name='Տեսականու Վերնագիր'),
        ),
    ]
