# Generated by Django 4.2 on 2023-04-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_indexpageassortment_assortment_barbeque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpageassortment',
            name='title',
        ),
    ]
