# Generated by Django 4.2 on 2023-04-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_remove_indexpageassortment_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexPageSliderActive',
        ),
        migrations.AlterModelOptions(
            name='indexpageslider',
            options={'ordering': ['id'], 'verbose_name': 'Գլխավոր Սլայդեր', 'verbose_name_plural': 'Գլխավոր Սլայդեր'},
        ),
    ]
