# Generated by Django 4.2 on 2023-04-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_delete_indexpagereviewsactive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='get_message',
            options={'ordering': ['-id'], 'verbose_name': 'Նամակներ', 'verbose_name_plural': 'Նամակներ'},
        ),
    ]
