# Generated by Django 4.2 on 2023-04-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_rename_about_us_title_ru_about_about_us_title_ruu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_us_title_ruu',
            new_name='about_us_title_fr',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='about_us_txt_ruu',
            new_name='about_us_txt_fr',
        ),
    ]
