# Generated by Django 4.2 on 2023-04-26 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_rename_about_us_title_fr_about_about_us_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpageassortment',
            name='assortment_title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Տեսականու Վերնագիր'),
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='assortment_title_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Տեսականու Վերնագիր'),
        ),
        migrations.AddField(
            model_name='indexpageassortment',
            name='assortment_title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Տեսականու Վերնագիր'),
        ),
        migrations.AddField(
            model_name='indexpagerefreshedmenu',
            name='refreshed_menu_item_text_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='indexpagerefreshedmenu',
            name='refreshed_menu_item_text_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='indexpagerefreshedmenu',
            name='refreshed_menu_item_text_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='indexpagerefreshedmenu',
            name='refreshed_menu_item_title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='indexpagerefreshedmenu',
            name='refreshed_menu_item_title_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='indexpagerefreshedmenu',
            name='refreshed_menu_item_title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='indexpageslider',
            name='slider_title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='indexpageslider',
            name='slider_title_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='indexpageslider',
            name='slider_title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='menu',
            name='cat_name_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.menucategories'),
        ),
        migrations.AddField(
            model_name='menu',
            name='cat_name_hy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.menucategories'),
        ),
        migrations.AddField(
            model_name='menu',
            name='cat_name_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.menucategories'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_name_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_title_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Տեքստ'),
        ),
        migrations.AddField(
            model_name='menucategories',
            name='category_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Կատեգորիայի Անուն'),
        ),
        migrations.AddField(
            model_name='menucategories',
            name='category_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Կատեգորիայի Անուն'),
        ),
        migrations.AddField(
            model_name='menucategories',
            name='category_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Կատեգորիայի Անուն'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='terms_title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='terms_title_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='terms_title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='terms_txt_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='terms_txt_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='terms_txt_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Վերնագիր'),
        ),
    ]
