# Generated by Django 4.2 on 2023-04-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_indexpageassortment_assortment_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_us_title_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_us_title_hy',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_us_title_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_us_txt_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_us_txt_hy',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_us_txt_ru',
        ),
    ]
