# Generated by Django 4.2 on 2023-04-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_about_about_us_title_en_about_about_us_title_hy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsandconditions',
            name='terms_title_en',
        ),
        migrations.RemoveField(
            model_name='termsandconditions',
            name='terms_title_hy',
        ),
        migrations.RemoveField(
            model_name='termsandconditions',
            name='terms_title_ru',
        ),
        migrations.RemoveField(
            model_name='termsandconditions',
            name='terms_txt_en',
        ),
        migrations.RemoveField(
            model_name='termsandconditions',
            name='terms_txt_hy',
        ),
        migrations.RemoveField(
            model_name='termsandconditions',
            name='terms_txt_ru',
        ),
    ]
