# Generated by Django 4.2 on 2023-04-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_remove_termsandconditions_terms_txt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Get_email',
        ),
    ]
