# Generated by Django 4.2 on 2023-04-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_delete_get_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50, verbose_name='Էջի Անուն')),
                ('img', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Նկար')),
            ],
            options={
                'verbose_name': 'Էջերի ՆԿարներ',
                'verbose_name_plural': 'Էջերի ՆԿարներ',
            },
        ),
    ]
