# Generated by Django 4.2 on 2023-04-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_pagepictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50, verbose_name='Էջի Անուն')),
            ],
            options={
                'verbose_name': 'Էջի Անուն',
                'verbose_name_plural': 'Էջի Անուն',
            },
        ),
        migrations.AddField(
            model_name='pagepictures',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_cat', to='main.pages'),
        ),
    ]
