# Generated by Django 4.2 on 2023-04-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_pages_pagepictures_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagepictures',
            name='page_name',
        ),
    ]
