# Generated by Django 4.2 on 2023-04-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_remove_pagepictures_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='background_image',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Ֆոնային Նկար'),
        ),
    ]
