# Generated by Django 4.2 on 2023-04-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_about_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_message',
            name='background_image',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Ֆոնային Նկար'),
        ),
        migrations.DeleteModel(
            name='PagePictures',
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
    ]
