# Generated by Django 4.2 on 2023-04-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_get_message_background_image_delete_pagepictures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Ֆոնային Նկար')),
            ],
            options={
                'verbose_name': 'Կոնտակտ Էջ',
                'verbose_name_plural': 'Կոնտակտ Էջ',
            },
        ),
        migrations.RemoveField(
            model_name='get_message',
            name='background_image',
        ),
    ]
