# Generated by Django 4.2 on 2023-04-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_contact_remove_get_message_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategories',
            name='background_image',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d', verbose_name='Ֆոնային Նկար'),
        ),
    ]
