# Generated by Django 4.2 on 2023-04-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_menucategories_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategories',
            name='background_image',
        ),
    ]
