# Generated by Django 4.2 on 2023-04-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_remove_menucategories_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicmodel',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
    ]
