# Generated by Django 4.2 on 2023-04-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_basicmodel_time_create_basicmodel_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategories',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծման Ամսաթիվ'),
        ),
        migrations.AddField(
            model_name='menucategories',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Փոփոխման Ամսաթիվ'),
        ),
    ]
