# Generated by Django 4.2 on 2023-05-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_remove_about_about_us_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_message',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Հեռ․ Համար'),
        ),
    ]
