# Generated by Django 4.2 on 2023-05-07 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_alter_get_message_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpagereviews',
            name='star',
        ),
    ]
