# Generated by Django 4.2 on 2023-05-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='person',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10),
        ),
    ]
