# Generated by Django 4.2 on 2023-05-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_remove_person_shirt_size_person_medal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
