# Generated by Django 4.2 on 2023-05-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_zone_facebook', models.URLField(verbose_name='Facebook Հղում')),
                ('food_zone_instagram', models.URLField(verbose_name='Instagram Հղում')),
                ('food_zone_glovo', models.URLField(verbose_name='Glovo Հղում')),
                ('food_zone_yandex_eat', models.URLField(verbose_name='Yandex Eat Հղում')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման Ամսաթիվ')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Փոփոխման Ամսաթիվ')),
            ],
            options={
                'verbose_name': 'Հղումներ',
                'verbose_name_plural': 'Հղումներ',
            },
        ),
        migrations.RemoveField(
            model_name='basicmodel',
            name='food_zone_facebook',
        ),
        migrations.RemoveField(
            model_name='basicmodel',
            name='food_zone_glovo',
        ),
        migrations.RemoveField(
            model_name='basicmodel',
            name='food_zone_instagram',
        ),
        migrations.RemoveField(
            model_name='basicmodel',
            name='food_zone_yandex_eat',
        ),
    ]
