# Generated by Django 4.2 on 2023-05-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_links_remove_basicmodel_food_zone_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='food_zone_menu_am',
            field=models.URLField(null=True, verbose_name='Menu.am Հղում'),
        ),
        migrations.AlterField(
            model_name='links',
            name='food_zone_yandex_eat',
            field=models.URLField(verbose_name='Yandex Eats Հղում'),
        ),
    ]
