# Generated by Django 4.2 on 2023-05-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_pagepictures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='about',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='pagepictures',
            name='description',
        ),
    ]
