# Generated by Django 4.2 on 2023-05-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_delete_contact_remove_about_background_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpageassortment',
            options={'ordering': ['id'], 'verbose_name': 'Տեսականի', 'verbose_name_plural': 'Տեսականի'},
        ),
    ]
