# Generated by Django 4.2 on 2023-05-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_alter_indexpageassortment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagereviews',
            name='customer_info_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Անուն Ազգանուն'),
        ),
        migrations.AddField(
            model_name='indexpagereviews',
            name='customer_info_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Անուն Ազգանուն'),
        ),
        migrations.AddField(
            model_name='indexpagereviews',
            name='customer_info_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Անուն Ազգանուն'),
        ),
        migrations.AddField(
            model_name='indexpagereviews',
            name='review_en',
            field=models.TextField(null=True, verbose_name='Մեկնաբանություն'),
        ),
        migrations.AddField(
            model_name='indexpagereviews',
            name='review_hy',
            field=models.TextField(null=True, verbose_name='Մեկնաբանություն'),
        ),
        migrations.AddField(
            model_name='indexpagereviews',
            name='review_ru',
            field=models.TextField(null=True, verbose_name='Մեկնաբանություն'),
        ),
    ]
