# Generated by Django 4.2 on 2023-05-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_indexpagereviews_customer_info_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagepictures',
            options={'ordering': ['id'], 'verbose_name': 'Էջերի Պատկերներ', 'verbose_name_plural': 'Էջերի Պատկերներ'},
        ),
    ]
