# Generated by Django 4.2 on 2023-05-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_alter_pagepictures_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepictures',
            name='decriptions',
            field=models.CharField(max_length=50, null=True, verbose_name='Էջի Անուն'),
        ),
    ]
