# Generated by Django 4.2 on 2023-05-10 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_rename_decriptions_pagepictures_decription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagepictures',
            name='decription',
        ),
    ]
