# Generated by Django 4.2 on 2023-05-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_pagepictures_decription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagePictures',
        ),
    ]
