# Generated by Django 4.2 on 2023-05-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_pagepictures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='food_zone_menu_am',
            new_name='food_zone_buy_am',
        ),
    ]
