# Generated by Django 4.2 on 2023-05-10 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_rename_food_zone_menu_am_links_food_zone_buy_am'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
    ]
